name = "OmicsProfiles"
uuid = "2c1f4335-9aeb-47fb-ad11-94d99429346c"
authors = ["Yueh-Hua Tu"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
